<?php
$items = is_array( $args['items'] ?? null ) ? $args['items'] : array();
$states = array( 'intro_request', 'student_absent', 'teacher_issue', 'replacement', 'term_review', 'flexible_term', 'google_problem', 'availability_conflict', 'admin_request' );
?>
<section class="dzn-tp-section" aria-labelledby="tp-attention"><div class="dzn-tp-heading"><div><p class="dzn-tp-kicker">نیازمند توجه شما</p><h2 id="tp-attention">کارهای مهم</h2></div><span><?php echo esc_html( sprintf( '%d مورد', count( $items ) ) ); ?></span></div><div class="dzn-tp-attention-grid">
<?php foreach ( $items as $index => $item ) : $valid = in_array( $item['state'] ?? '', $states, true ); ?>
 <article class="dzn-tp-attention-card is-<?php echo esc_attr( $valid ? $item['state'] : 'unknown' ); ?>"><p class="dzn-tp-state"><span aria-hidden="true">◆</span> <?php echo esc_html( $valid ? ( $item['due'] ?? 'نیازمند بررسی' ) : 'وضعیت ناشناخته' ); ?></p><h3><?php echo esc_html( $valid ? ( $item['title'] ?? '' ) : 'این مورد در دسترس نیست' ); ?></h3><p><strong><?php echo esc_html( $valid ? ( $item['context'] ?? '' ) : '' ); ?></strong></p><p><?php echo esc_html( $valid ? ( $item['message'] ?? '' ) : 'برای امنیت، همهٔ اقدام‌ها پنهان شدند.' ); ?></p>
 <?php if ( $valid ) : ?><div class="dzn-tp-actions"><button class="dzn-button" type="button" data-dzn-tp-open="tp-action-<?php echo esc_attr( $index ); ?>"><?php echo esc_html( $item['primary'] ?? 'بررسی' ); ?></button><?php if ( ! empty( $item['secondary'] ) ) : ?><button class="dzn-button dzn-button--secondary" type="button" data-dzn-tp-open="tp-action-<?php echo esc_attr( $index ); ?>"><?php echo esc_html( $item['secondary'] ); ?></button><?php endif; ?></div>
 <dialog id="tp-action-<?php echo esc_attr( $index ); ?>" class="dzn-tp-dialog" aria-labelledby="tp-action-title-<?php echo esc_attr( $index ); ?>"><div><button type="button" class="dzn-tp-close" data-dzn-tp-close aria-label="بستن">×</button><h2 id="tp-action-title-<?php echo esc_attr( $index ); ?>"><?php echo esc_html( $item['title'] ?? '' ); ?></h2><p>این کنترل فقط پیش‌نمایش رابط آینده است؛ هیچ اطلاعات یا حقیقتی ثبت نشد.</p><?php if ( 'intro_request' === $item['state'] ) : ?><fieldset><legend>چند زمان جایگزین نمایشی</legend><label><input type="checkbox"> یکشنبه ۱۸:۰۰</label><label><input type="checkbox"> سه‌شنبه ۱۹:۳۰</label><label><input type="checkbox"> پنجشنبه ۱۷:۰۰</label></fieldset><?php elseif ( in_array( $item['state'], array( 'replacement', 'flexible_term' ), true ) ) : ?><label>تاریخ نمایشی <input type="date" disabled></label><label>ساعت نمایشی <input type="time" disabled></label><?php elseif ( 'term_review' === $item['state'] ) : ?><ol class="dzn-tp-schedule-summary"><?php for ( $i = 1; $i <= 12; $i++ ) : ?><li>جلسهٔ <?php echo esc_html( $i ); ?> · شنبه</li><?php endfor; ?></ol><?php endif; ?><button class="dzn-button" type="button" data-dzn-tp-presentation>ادامه در آینده</button><p class="dzn-tp-action-status" aria-live="polite"></p></div></dialog><?php endif; ?>
 </article><?php endforeach; ?></div></section>
